### ISSUE TITLE
Merge alcoholic beverage (FOODON_00001579) with beverage alcohol FOODON_03310661 ?

### ISSUE THREAD

**Issue by LCCarmody** [FoodOntology/foodon#104]
This is just a suggestion but I think 'alcoholic beverage' (FOODON_00001579) should be merged with 'beverage alcohol' (FOODON_03310661 )?

As far as I can tell, these refer to the same thing, but possibly one was imported from somewhere?  
Anyways, for my purposes, 'alcoholic beverage' is what I want and will change it on my end.

**Comment by cmrn-rhi** [comment]
Thank you for drawing attention to this issue. After reviewing these (and other terms) I don't think we should merge the suggested terms as "**alcoholic beverage**" is broad enough to encompass non-distilled and distilled beverages whereas "**beverage alcohol**", and it's almost identical counterpart "**beverage (alcoholic, distilled)**", are specifically distilled beverages. The former two only differ because "beverage alcohol" has the quality 'fully heat-treated' in an rdfs:comment SIREN DB annotation (but it doesn't actually show up in description relationships).

I think we should merge "**beverage alcohol**" and "**beverage (alcoholic, distilled)**" and rename it something along the lines of "**alcoholic beverage (distilled)**". I'll include the "heat treated" quality from "**beverage alcohol**" because true spirit distillation always involves heat treatment. They could also possibly be combined with "**distilled spirit**" which is already a subclass of "**alcoholic beverage**".

There are spirits that are said to be treated with cold/freeze distillation but that is a misnomer because it is not actually distillation but rather a solution enrichment/concentration via fractional freezing. Thus, I could also add "**alcoholic beverage (fractional freezing)**" or "**alcoholic beverage (cold distilled)**" to cover this category.

**SUGGESTION 1)**
"**alcoholic beverage**" encompasses distilled and non-distilled alcohol.
"**alcoholic beverage (distilled)**" refers to true distilled alcohol, has heat-treated quality. Can be combined with "distilled spirit".
"**alcoholic beverage (cold distilled)**" refers to fractional freezing, non-true cold distillation alcohol isolation processes.

**SUGGESTION 2)**
"**alcoholic beverage**" encompasses distilled and non-distilled alcohol.
"**alcoholic beverage (distilled)**" refers to any distilled alcohol. Can be combined with "distilled spirit".
"**alcoholic beverage (heat distilled)**" refers to true distillation alcohol isolation processes AND is a subclass of "**alcoholic beverage (distilled)**".
"**alcoholic beverage (cold distilled)**" refers to fractional freezing, non-true cold distillation alcohol isolation processes AND is a subclass of "**alcoholic beverage (distilled)**".

With either suggestion, I'll be sure to review annotations on all the terms to make sure they are comprehensive and clear.

**Comment by LCCarmody** [comment]
Renaming 'beverage alcohol' would be good. I am okay (indifferent) to the other mergers suggested, but I highly recommend adding a specific definition to clarify some of what you said.

For my use, I needed 'alcoholic beverage' (but accidentally selected 'beverage alcohol' ) and 'beer'.  After reasoning, I was confused as to why 'beer' was not a child of 'beverage alcohol'.  

 So, in whichever version you go with, consider the Descendents when choosing the structure.

**Comment by LCCarmody** [comment]
Thanks for doing this!

**Comment by ddooley** [comment]
This is now in our foodon-edit.owl draft

**Comment by ddooley** [comment]
loaded up live.

**Comment by LCCarmody** [comment]
thanks!
