### ISSUE TITLE
mammal hierarchy is bonkers; and: soylent green is...

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#108]
![image](https://user-images.githubusercontent.com/50745/81896411-68c3f980-9569-11ea-890e-5472935262ae.png)

amphibians and fish are not mammals

equine is an adjective

most of the mammals there don't look like fiat object parts. Maybe Cat is when it blends into sofa. IMO 'fiat object part' is a terrible class anyway (cc @pbuttigieg). It should at least have logical axioms that could make explicit to a reasoner why a fish is not a fiat object part. This is also a useful lesson in being careful in stitching different ontologies together.

Why is "deer family" there and not singular deer? Is it necessary to eat the whole family? That's barbaric. At least let poor Bambi go free.

this seems to a weird mix of ID spaces. Why is NCIT used for taxa? Why does foodon mint its own mammal?

**Comment by cmungall** [comment]
This is my favourite:

![image](https://user-images.githubusercontent.com/50745/81896753-1f27de80-956a-11ea-8fc1-c013d0ad7923.png)

If I understand correctly, humans that produce milk can be eaten. However, humans that do not produce milk are not on the menu

This sounds odd, but if you look at the equivalence axiom, anything that has a taxonomic identifier of homo sapiens is equivalent to human as a milk source. So all humans are milk sources. Therefore all humans are food.

Soylent green by reasoning, I love it

**Comment by ddooley** [comment]
Thanks for taking the time to dive into this.

Hmm, it seems the OLS version is out of date - the amphibian and fish classes are not under mammal and haven't been for a while (a mistake spotted earlier).

We're having a call tomorrow with Pier about where upper level food material class terms should be positioned better, so we can solve the fiat part thing then.  I sense a withdrawl is in the wind from using fiat part as much.

I get "deer family" conveys something broader than what we meant - a member of deer family or genus, so we'll work on that.

I have to grin wryly about the 'humans as milk source' class.  Idea was to accept that humans - specifically lactating women - can provide a food source to infants without implying that they themselves are eaten cannibalistically.  The food source class branch lists WHOLE ORGANISMS  that can provide food in some way.  I take your point, so I think we should switch in 'lactating woman' in there instead.  But "food source" class didn't mean necessarily that the whole organism is consumed, e.g. apple tree.

Throughout FoodOn we've switched to RO 'in taxon' rather than the 'has taxonomic identifier' ... construct.

I asked NCIT a while back if they would be willing to take on all the organisms that FoodOn has, but didn't hear back.  I was trying to practice MIEROT reuse of NCIT references thinking that they may show up in papers here and there but their list isn't very comprehensive.  A 'food source' reference is meant to be a reference to the whole organism (and that includes oddities like tree splices that don't have a single taxon, as well as ambiguous references like "spinach" which can map to multiple kinds of plant, among other examples), hence this branch is a step removed from NCBITaxon, which as I understand it doesn't commit to organism wholeness in the reference?

We should rename equine to "equine animal".

Appreciate that soylent green is algae of human remains.  It may merit a FoodOn entry, perhaps under a "taboo food product" class!

**Comment by mcourtot** [comment]
I should point out that production of milk is not limited to human women - see for example https://pubmed.ncbi.nlm.nih.gov/6420385/.
While it doesn't seem to be intended for feeding in those cases (i.e. lactation as the process of producing food for infants seems to happen naturally only in women), this wouldn't be excluded from the current definition of foodon product type, http://purl.obolibrary.org/obo/FOODON_00001002

Probably too esoteric, but I blame @cmungall for choosing click-bait GH issue titles :)

**Comment by cmungall** [comment]
Also male dayak bats may lactate, reasons not clear, possibly as
supplemental food source

**Comment by cmungall** [comment]
fiat object part: if you really want it, infer it, and ensure you have disjointness axioms to catch incoherency

but I think it does nothing for our users other than forcing them down an extra level

**Comment by cmungall** [comment]
> The food source class branch lists WHOLE ORGANISMS that can provide food in some way.

Should be more explicit but I wonder if this shouldn't be done with annotations (in the GO sense). E.g. put into globi

**Comment by ddooley** [comment]
Good talk with Pier and Ramona this morning.  We're most likely moving away from fiat object part.  As well, looking closely at using NCBITaxon species as whole organism references in many cases, while turning to some equivalence classes where necessary (e.g. spinach = 5 species of plant, apple tree = "Malus pumila or Malus domestica" etc.)

**Comment by ddooley** [comment]
OLS is looking into ontology sync problem: https://github.com/EBISPOT/OLS/issues/363

**Comment by ddooley** [comment]
So the fish/amphibian problem is back on me.  I'd been running the hermit reasoner on FoodOn on command line because it seemed to take forever in Protege.  As a result I was only taking care of unsatisfiability issues but not spotting odd inferences like the above.  I've removed an equivalence that was way too broad, so this problem should be fixed.  Thanks to James at OLS for debugging this!  

Going into the future I'll try to find a way to get a differential report on new inferences in order to check for oddballs.

**Comment by cmungall** [comment]
you know my take, most axioms outside EL++ are probably wrong and not
saying what you think they say. At best, they are weaker than you think
they are. Trust the Elk. Always have a trusty Elk running in Protege, the
Elk has never failed me. Use the el-shunt pattern to localize necessary
disjunctions etc and materialize these ahead of time.

We should have more standard ways of checking reasoner diffs in ODK. E.g.
save a file of only subClassOf axioms post-reasoning, save as something
readable like obo, and check the diffs

Also: less need for visual checking if you have sufficient disjointness
axioms. Most ontologies are way underpowered here. Disjointness axioms are
great. all nodes in ncbitaxon are PD. I think we make a bridge file with
these axioms in it as part of release?

**Comment by ddooley** [comment]
Issue fixed now and ok on OLS.
