### ISSUE TITLE
Cheese subparts

### ISSUE THREAD

**Issue by stheil15** [FoodOntology/foodon#129]
Hi,
I am submitting 16S amplicon sequencing data to the EBI ENA. I have 3 types of samples, cow milk, cheese rind and cheese core. I have found the two first terms in the ontology, but i miss the "cheese core" term. We defined core as the center of the cheese.

I already ask the ENVO ontology in this [thread](https://github.com/EnvironmentOntology/envo/issues/1076).

Thanks,
Sebastien

**Comment by ddooley** [comment]
We're happy to add cheese core, perhaps with simple definition that puts it in relation to the surrounding rind.

term: cheese core
definition: 'part of' some cheese and 'surrounded by' some cheese rind.
This avoids the anaerobic issue of having pockets of air & attendant microbiomes.
Would that suffice?

Is there a helpful web link to add for further information?
Want your ORCID included in term editor?

Cheers,

Damion

**Comment by stheil15** [comment]
Thank you.
That is perfect and I agree with the definition.

This publication from our lab define and use the term "cheese core" :
https://www.nature.com/articles/s41598-017-18447-y

My ORCID : 
https://orcid.org/0000-0001-7361-4159

Again, many thanks.
Sebastien

**Comment by ddooley** [comment]
Ok, new **cheese core** term id is: http://purl.obolibrary.org/obo/FOODON_00003841 .
Slightly different plain english definition: A cheese food product which is surrounded by a cheese rind.

As well I added a new generic **cheese rind** term to cover natural/artificial etc. rinds: http://purl.obolibrary.org/obo/FOODON_00003842 : "A food rind which is a natural or artificial exposed layer that surrounds a cheese core." Somewhat ambiguous since some rinds are inedible, and therefore not quite food products.

I know the definitions are somewhat circular but anything surrounded by anything tends to be that way!

These will be online within a week.

Ciao,

Damion
