### ISSUE TITLE
Is EFSA in the mix?

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#13]
@wwhsiao @mateolan @Public-Health-Bioinformatics @griffiemma 
Just wondering if one of the classification schemes we will import include the European Food Safety Authority (EFSA) codes...

**Comment by Public-Health-Bioinformatics** [comment]
I was thinking we could do this in a targeted way.  Both Langual and FoodEx2 were occasionally cross referencing their terms so insofar as we import a Langual Facet we may have DBXref's to FoodEx2 codes.  FoodEx2 doesn't have a "Food Source" facet like Langual does; and other facets like food preservation aren't identical.  I could try (for example) to provide a food preservation facet that takes into account both Langual, FoodEx2, and with CHEBI terms (https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_78295) forming the foundation where suitable.

One way Langual has tried to approach the fact that there are many classification systems out there, is to offer different sub-hierarchies in its Facet A Product Type – European / International / USA / Other.  E.g. http://www.langual.org/langual_thesaurus.asp?termid=A0690&haschildren=True&owner=A0356&openstr=00000_A0361_A0356    A first approach could be to DBXRef food terms in our "pure" ontology over to these other system's equivalents.

D.

**Comment by Public-Health-Bioinformatics** [comment]
Latest news is that LanguaL is improving their EFSA FoodEx2 coverage.  I'll report on that when I hear more from the LanguaL curators.  We should be able to pass these LanguaL changes into FoodOn when they are released.

**Comment by behrica** [comment]
I am Carsten Behring, Data scientist from EFSA, and want to make an unofficial comment here:

There is a bit of an new interest in EFSA regarding ontologies. I cannot speak for my scientific colleges,
so I don't know in which directions EFSA will go.

FoodEx2 is of course very relevant for us and I heard comments on CHEBI as well.

I can from my point of view make a "problem statement", which I would like to see solved with the help of ontologies in the future:
EFSA (and me personally) is requested to extract data/knowledge/information from an ever growing number of scientific articles and other type of unstructured data sources.
Doing so automated is, in general,  a very hard problem, as it requires "human level capability" of text understanding which is still far away, if it ever arrives.

So the logical consequence is to turn the problem around. Instead of asking computers to extract knowledge from text, we should request humans to express their knowledge in an structured way.
And here I see the place for ontologies.

**Comment by Public-Health-Bioinformatics** [comment]
Hi Carsten,
Good to hear about your & EFSA's general interest.  We are keen to hear your thoughts on how FoodEx2 might be integrated with FoodOn more closely?  We're also very interested in curation of both existing datasets via text-mining to ontology mapping, as well as starting out with pure ontology-driven data description.  On the former front we're having some success with sample metadata specific to foodborn pathogens due to an open source text-processing pipeline that a colleague, Gurinder Gosal, has put together, which he will publicize soon. It depends on FoodOn and other domain specific OBOFoundry ontologies.  Its a smaller problem domain as it doesn't have to address the subtleties of full text comprehension.  As you say humans still have to review what these systems come up with though.

About your last point, we're aware that ontologies are so far not easy to incorporate into existing systems, so we've been developing GEEM, as a gateway to provide FoodOn ontology driven vocabulary specifications. A form that specifically details a number of facets of a food sample is at http://genepio.org/geem/form.html#GENEPIO:0002106) - including some form type-as-you-go functionality for locating terms in long lists, and by synonym (best viewed in Chrome). Certain user interface features need to work well before ontologies will be adopted happily. We're aiming to encourage new projects to take on controlled vocabulary by offering it up in more convenient formats.

At any rate, we would be happy to engage on these aspects, and hear more about EFSA ontology ambitions in the future!

Damion Dooley

**Comment by Public-Health-Bioinformatics** [comment]
One other link - this shows FoodOn food descriptors at work in the context of a broader "draft sequence repository contextual data standard" ontology driven specification: http://genepio.org/geem/form.html#GENEPIO:0002083 . Knowing how much FoodEx2 terminology is at use in various agencies, I can see the allure of having food samples described by FoodEx2 become mappable to this.

**Comment by Public-Health-Bioinformatics** [comment]
So I just had an update from LanguaL / Danish Food Informatics and they say FoodEx2 mapping will be introduced to LanguaL, probable launch in april.  As well the GS1 tree will be updated, which is great news.  We'll be able to import the resulting Facet A changes into FoodOn without much trouble thereafter.

**Comment by Public-Health-Bioinformatics** [comment]
The "Exposure" facets from EFSA FoodEx2 have now been incorporated by the LanguaL team into LanguaL: http://www.langual.org/langual_thesaurus.asp?termid=A1895&haschildren=True&owner=A0356&openstr=00000_A0361_A0352_A0356
We look forward to importing this hierarchy into FoodOn in the next month.

**Comment by Public-Health-Bioinformatics** [comment]
EFSA FoodEx2 Exposure hierarchy is now in FoodOn, as well as an updated GS1 hierarchy.  In the next year we will be studying solutions for how to cross-reference these categories with the other existing product type categories inherited from LanguaL, as well as FoodOn's ontology-oriented "foodon product type".
