### ISSUE TITLE
Change class name "vitis aestivalis" to "Norton grape plant"

### ISSUE THREAD

**Issue by DianeKEPR** [FoodOntology/foodon#142]
Change class name "vitis aestivalis" to "Norton grape plant" to be consistent with Latin and common names.
other synonyms "Pigeon grape plant" and Summer grape plan"
The Norton grape plant is native to eastern North America.  Noted for deep blue-purple pigmentation, the skin of Norton grapes has a higher content of total anthocyanins than other purple grape cultivars such as the Concord grape.
https://en.wikipedia.org/wiki/Norton_(grape)

**Comment by ddooley** [comment]
So FoodOn uses NCBITaxon terms - which all have latin names - wherever possible for whole organism references, and we can't change their primary labels, but we can offer alternate ones via "alternative term" annotation, or synonyms in FoodOn if desired.  One can switch protege to display "alternative term" for all terms by default, then label if alt. term isn't present. This can be implemented in user interfaces too. The approach allows term to be found by both labels.

FoodOn also has its own native FOODON_12345678 identifier terms for plants (and animals) which have common names, but these come into play only in a few cases:
- where no NCBITaxon organism exists for that organism or varietal.
- where we haven't yet found an NCBITaxon organism. Its a work in progress to convert all unmatched FoodOn terms to NCBITaxon ones, though we have matched thousands already.
- where FoodOn is offering a more common language "convenience" grouping of plants, like "spinach plant" that have no NCBITaxon equivalent because the grouping cuts across NCBITaxon taxonomic clades.

**Comment by DianeKEPR** [comment]
Curious question (not implying a right or wrong purpose): what audience is the primary intended user of Foodon?  Do food production users work through a Latin primary term?   Is the intended audience an interoperability with an ontology or other Food Industry organization that uses Latin as the preferred name?   Queries to get an answer that returns with multiple results would yield a list of Latin names.   Trying to better understand the fit for purpose use case for this.   Is it that there exists many species of "spinach plant" that can only be distinguished by the Latin term and have no common name but has significant variations in nutrition, processing, other information of importance for users of Foodon?

**Comment by ddooley** [comment]
There is a tension between technical and non-technical use of the ontology.  Technical users - at FDA for example, with respect to seafood items - know they have to reference scientific names when it comes to testing a product because market names are too ambiguous.  I totally understand non-technical users (e.g. within the context of a food product catalogue) would prefer common names.  I think you will see the same tension playing out in Wikipedia - which has increasingly shifted to using latin names for food organisms, and offering common name synonyms.  And yes "spinach" refers to over 5 different species of plant depending on where one is on the planet.  

Personally I think we have to encourage people to think of the ontology as potentially 1 step removed from public-facing user interfaces, and provide a way - through "alternate term" to provide common names or primary names for organisms in such interfaces. I feel that is the only way to enable both technical and non-technical users.   Does that sound like a decent compromise?

Luckily we only face this difficulty in the whole organism reference branch (roots and all); by the time it comes to naming anatomical part x taxonomy, we can slip back into common name world: so we get to say "Norton grape" as a food product, rather than "Vitis aestivalis grape".

**Comment by ddooley** [comment]
We have added the exact synonyms you mention so this will be available on next release.
