### ISSUE TITLE
FOODON is injecting axioms into CHEBI causing incoherencies

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#154]
FOODON is injecting an axiom "vitamine E" subClassOf 'food soluble vitamin'. In CHEBI these are structures and roles respectively. This causes incoherency when FOODON and CHEBI are combined. FOODON alone masks this as you are rewiring the chebi role to be a structure

https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_24020&viewMode=All&siblings=false

![image](https://user-images.githubusercontent.com/50745/127934585-327e7911-b46b-4e67-9794-17bb3bb2cc82.png)

I think this was originally reported here #42 but that was closed

**Comment by cmungall** [comment]
It looks like this was discussed in an issue over here with very many comments: https://github.com/Southern-Cross-Plant-Science/cdno/issues/57

That issue has many interesting points, however, it is absolutely imperative that we don't inject axioms that cause incoherencies. I realize the CHEBI labels are very confusing. However, the fix is not to rewire. This just bundles up a pandora's box full of incoherencies that break downstream ontologies. Just use the CHEBI classes in a way that is consistent with their *logical* classification. 

See also https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443

**Comment by ddooley** [comment]
CDNO led a call over a month ago with a CHEBI curator to straighten out their role and chemical entity branches for vitamins (there will be two branches, and role branch will have "role" explicit in labels.  As soon as CHEBI publishes their August release we (FoodOn and CDNO) will be able to align with their terms and the problem should be solved downstream in FoodOn.  

Right now FoodOn is importing CDNO "dietary nutrition component" that has CHEBI vitamin as a subclass - indeed it is a role and so that's the problem.  But apparently the new, needed CHEBI terms are just days or weeks away from being released.

**Comment by ddooley** [comment]
Just awaiting an OntoBee/OntoFox update for new CHEBI so we can import changes and then make correction.

**Comment by ddooley** [comment]
Still waiting - a different OntoBee refresh bug is preventing latest CDNO from being loaded.

**Comment by cmungall** [comment]
can you use robot?

**Comment by ddooley** [comment]
This should be fixed now.  OntoBee just updated CDNO which had the CHEBI fix in it; FoodOn has now imported this and has a release.

**Comment by ddooley** [comment]
I'll close this; reopen if still an issue somehow.
