### ISSUE TITLE
NTR: multiple terms

### ISSUE THREAD

**Issue by KaylaPenn** [FoodOntology/foodon#199]
On Google Drive: https://docs.google.com/spreadsheets/d/1x_CQJQXhm4GEjqeCxhtixz2Tx-mdonyh/edit?usp=sharing&ouid=105953967042001104555&rtpof=true&sd=true

**Comment by cbarcl01** [comment]
Hi @KaylaPenn,

Thanks for sharing your google sheet for 73 New Term Requests for FoodOn - the information and links you provided were really helpful. We are currently processing this and require some clarity around some of the requests. These have been added to a separate sheet, linked (note we've mapped your raw data to a ROBOT table for our import process) [FoodOn Issue 199 N/A Term Requests](https://docs.google.com/spreadsheets/d/1BFoBzZVmM8EMG2JfQAQ_1V0bJysrKvZmZYgeRGsxzcY/edit?usp=sharing).

Under **'Term Requested'** (**'New term'** in your original google sheet), these rows are assigned **N/A** - could you clarify what is required for these requests? Are these NTR's that you need us to suggest a label for? Or are they requests to change an existing term (i.e. the parent term by adding a synonym or definition)?

The FoodOn team are currently working on a template for bulk NTR's which will hopefully streamline this process for everyone - in the meantime, I've added some questions under a column **'Issues/Notes'**. If you would be able to provide some context that would be great (you can added feedback directly to the 'Issues/Notes' field, or if you could update the 'Term requested' column to the term you would like). 

I hope this all makes sense, please let me know otherwise! Thanks again for the detailed list, we are looking forward  to making  progress on this for you as soon as possible. I hope you are having a great week.

Cheers,
Charlie

**Comment by KaylaPenn** [comment]
Hi @cbarcl01,

For rows with **'Term Requested'** == N/A, these are all requests to add an exact or near synonym to an existing term. The proposed synonym is under the column **'New synonym'** in the original sheet and **'english broad synonym'** in the new sheet. For example, I asked that 'calabrese salami' be a synonym for Italian-type salami FOODON:035421.

Side note, in the original sheet, there are instances where ';' was mistakenly used instead of '|' to separate terms: rows 4, 30, 55 and 57; row 6 in the new sheet.

Please let me know if you have any other questions and thank you for your work.

Best,
Kayla

**Comment by cbarcl01** [comment]
Hi @KaylaPenn 

Thank you so much for your speedy reply! That certainly clarifies things - thanks for that. 

No problem - I'll double check all the delimiters and make sure to use the pipe for the items described. 

I'll keep you updated with progress, in the meantime I hope you have a great weekend.

Best,
Charlie

**Comment by KaylaPenn** [comment]
I will not operate this GitHub account after July 20th. Please contact Dr. Ruth Timme (https://github.com/retimme) for any further questions or comments. Thank you.

**Comment by cbarcl01** [comment]
Hi @retimme

Thanks for taking over these requests in Kayla's absence. We are currently working on these requests and I have a couple of clarifications I hope you can assist with.

From Kayla's original Google sheet:

- Row 20, new term **'hoodia'**, is this product specifically derived from the species *Hoodia gordonii* only, and if so is it derived from a specific part of the plant?
- Row 35, are you happy for **'food (compounded)'** to be a synonym of **'food (salted)'**, where the definition for food (salted) is "A food product which is output of a salting process where salt is dissolved or absorbed into the food as an ingredient or flavourant", or would a new term be preferred?
- Row 45, to confirm for the new term **'poison'**, is this supposed to refer to an item that is poisonous as a quality, or rather as a noun, to define a chemical that is a poison? 

Thank you in advance for your help.

**Comment by cbarcl01** [comment]
The terms from this issue have been added, and the relevant synonyms applied. The assigned Term and ID can be viewed in this [google sheet](https://docs.google.com/spreadsheets/d/1o_n0NIdPIMf8OamOn2nx8NczYyOXtqItr3fDq7fVJxY/edit?usp=sharing), along with comments.

Please let us know if any of the terms in this sheet need amending, or if you have feedback and we can reopen this ticket.

Thanks.
