### ISSUE TITLE
NTR: multiple preservation terms

### ISSUE THREAD

**Issue by KaylaPenn** [FoodOntology/foodon#202]
# NTR: no preservation administered or intended

## Parent Term/Class:
 ‘food preservation process’ FOODON:03470107

## Definition: 
intentional and intended lack of an applied method to prevent or slow microbial, enzymatic or oxidative spoilage

# NTR: preservation intended but not yet administered

## Parent Term/Class:
 ‘food preservation process’ FOODON:03470107

## Definition: 
method to prevent or slow microbial, enzymatic or oxidative spoilage not applied, but intended to be so

**Comment by ddooley** [comment]
These two class terms have a future tense aspect to them that we haven't actually had in FoodOn so far. I think these are information content items about an object with respect to a process, rather than a subclass of a process itself. I'd organize them under "food datum". 

    "food datum"
      "food preservation datum"
        "no food preservation administered or intended"
        "food preservation intended but not yet administered"

Where a 'food preservation datum' :

    - 'is about' some 'food product' 

and "food preservation intended but not yet administered":

    - 'is about' some 'food preservation process'

We could use them then to say:

[instance of "food preservation intended but not yet administered"]
      'is about' 'blanched tomatoes sample 123'
      'is about' 'food canning process'

(Technical note, a reference to a process that has not occurred (has not yet been instantiated) would have to be done via punning to a generic class instance; that may be useful for then talking about aspects of the eventual process ).
 
P.s. there is one definition for "food product": "Food material for humans and animals which is processed with the intention that it be consumable as a whole or added to other food products." But that is the only class that mentions the word "intended", which is basically a statement of objective of the food processing. I guess we could have reworded "food product" as an output of a process having a possible goal of being consumable etc.

**Comment by KaylaPenn** [comment]
Makes sense. Have a happy weekend!

**Comment by ddooley** [comment]
I think we should break these terms up into fact and intention.  One would just apply both datums to get at the "or" disjunction.  Can we say "planned" instead of "intended"? And would "applied" be ok instead of "administered"?

food preservation applied
food preservation planned
no food preservation applied
no food preservation planned

**Comment by KaylaPenn** [comment]
I will not operate this GitHub account after July 20th. Please contact Dr. Ruth Timme (https://github.com/retimme) for any further questions or comments. Thank you.

**Comment by cmrn-rhi** [comment]
> I think we should break these terms up into fact and intention. One would just apply both datums to get at the "or" disjunction. Can we say "planned" instead of "intended"? And would "applied" be ok instead of "administered"?
> 
> food preservation applied food preservation planned no food preservation applied no food preservation planned

@retimme can you comment on this?

**Comment by ddooley** [comment]
I have created 4 terms as listed above, in the foodon-edit.owl file.  I will close this now, but can reopen if any more feedback / debate comes in.
