### ISSUE TITLE
cod class wrong parent?

### ISSUE THREAD

**Issue by marieALaporte** [FoodOntology/foodon#219]
The [cod class](http://purl.obolibrary.org/obo/FOODON_03411423) (FOODON_03411423) has two parents: 'cod familly' and 'cod food product'. I believe only 'cod familly' is correct here.

**Comment by marieALaporte** [comment]
Same for anchovy which is both under a fish hierarchy and food product. So maybe I am not understanding the structure correctly

**Comment by ddooley** [comment]
Briefly, this is the connundrum:  Can all the whole fish taxon references be considered food products?   I am considering disconnecting all the "X food product" parents, but then do we have to create a mirror "whole fish" for each NCBITaxon just to refer to it as a product in a store or fish pen etc.? What do you think?

**Comment by ddooley** [comment]
The FoodOn curation team has decided to disconnect all common language whole organisms from the "food product hierarchy" since they are meant to be referenced from other contexts besides food products. We have disconnected cod from "cod food product", and "anchovy" from "anchovy food product".  We'll do the same for other dual parent whole organism references.
