### ISSUE TITLE
Two weird terms found their way into the latest FOODON release

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#269]
Careful, they are used in axioms! (read the IRI)

```
    <!-- http://purl.obolibrary.org/obo/foodon.owl/FOODON_03602001 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/foodon.owl/FOODON_03602001"/>
    


    <!-- http://purl.obolibrary.org/obo/foodon.owl/FOODON_03602002 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/foodon.owl/FOODON_03602002"/>
    
```

**Comment by ddooley** [comment]
I see the axiom + deprecation problem in FOODON_03602001 and that is now fixed in foodon-edit.owl

I see we have a few wrong URIs : http://purl.obolibrary.org/obo/foodon.owl on some entities over the year(s). 

![image](https://user-images.githubusercontent.com/4000582/219761499-ee0802e5-2816-4df0-84ef-756aef850648.png)

 They are now fixed on live /foodon.owl !  Thanks for spotting this.  I was wondering if ODK can spot these?  We haven't upgraded to latest ODK yet.

[EDIT] I realize ODK probably can't validate URI's willy-nilly unless it had the entire namespace of possibilities.  But can it spot use of deprecated terms in axioms?

**Comment by matentzn** [comment]
Yes (deprecated) because it is using robot report to do so. It's not perfect, ie it has trouble with very complex axioms, but in general it works. 

Your URI issue can be easily prevented by adding a custom sparql query to your setup. Are you using the proper ODK repo Lay-out?

**Comment by ddooley** [comment]
Good to know about deprecated terms.  

I have to upgrade FoodOn's ODK, its actually 5 years out of date!   But one of the things is my file import pipeline uses OntoFox to select specific import terms; and casts all import files as well as foodon-edit.ofn - in owl functional notation, which has helped minimize diffs.  On ODK board it seemed like having the whole backend file system leading up to finished ontology.owl file was geared to .owl files?  So I worry that FoodOn's build doesn't sound like it would work out of the box with ODK.

Closing this thread as its resolved now.
