### ISSUE TITLE
Two labels of mushroom

### ISSUE THREAD

**Issue by zhengj2007** [FoodOntology/foodon#27]
http://purl.obolibrary.org/obo/FOODON_00001287 mushroom has two rdfs:label, both values are 'mushroom' but one with datatype string, the other with language: en. Is it better to remove the label with datatype string to make it consistent with other FOODON terms?

In addition, FOODON:mushroom hasSynonym: wild mushroom; fungi. All mushroom is Fungi but not all Fungi is mushroom. In addition, not all wild mushroom is food source. It can be fixed by changing it to boardsynonym.

**Comment by Public-Health-Bioinformatics** [comment]
Thanks for catching that!  I've dropped the one originating in Envo.  Will look at the fungi/mushroom issue shortly....

**Comment by Public-Health-Bioinformatics** [comment]
So we could say 
   FOODON:mushroom hasBroadSynonym: fungi
and
   FOODON:mushroom hasNarrowSynonym: wild mushroom
and leave it at that?

Side note: we do have "wild mushroom (raw)" as a food product term in our SIREN food product slim (its not integrated into foodon.owl yet because we need to clean it up first, but it will provide FoodOn ids for its 9600+ food products).  The "wild" part is of course referencing where it is gathered which is enough to get it treated as a food product category.  However, it is still appropriate to have "mushroom" have a narrow synonym "wild mushroom".  

A more linguistic treatment would introduce the pattern "[food source] and gathered from undomesticated location" = "wild [food source] product".  It does look like we need to define the concept of wild = found or gathered food, vs. "domesticated" = farmed, herded etc, probably in FoodOn.  There are lots of "wild" food products.

**Comment by Public-Health-Bioinformatics** [comment]
Also I just looked at the definitions of "mushroom" and "edible mushroom" in Wikipedia.  I think FoodOn can use the straight "mushroom" defn. as is, and also have a separate, more human-focused "edible mushroom" term.

**Comment by Public-Health-Bioinformatics** [comment]
any more feedback?

**Comment by zhengj2007** [comment]
All proposed changes look good to me.
