### ISSUE TITLE
Update FOODON/tooling to lastest owl API

### ISSUE THREAD

**Issue by kaiiam** [FoodOntology/foodon#270]
In case anyone on the team missed it, there's been a rather large update to all the relevant tools ROBOT 1.9.3, ODK 1.4 and Protégé 5.6.1, all of which are now using the  new version of the OWL API, 4.5.25. 

The instructions from the OBO community slack message were to:
1. (When using ODK), pull the latest image and update your repository as per the usual procedure. Once the repository is updated, you might want to try a “mock release” and carefully check all the generated files.
2. Open your main ontology file (the “-edit” file, if you’re using an ODK-based layout) with the new version of Protégé and forcefully save it, without introducing any ontological change.
3. Commit the newly saved -edit file.
4. From that moment on, the edit file should never again be edited with Protégé < 5.6.0, so if your ontology is worked on by several people, make sure they all upgrade their version of Protégé.

No rush on this, but we'll need to do this prior to pushing any changes to FOODON. Thankfully we don't have any outstanding PRs.

**Comment by ddooley** [comment]
So Protege 5.6.1 is available via: https://github.com/protegeproject/protege-distribution/releases/tag/protege-5.6.1
I encourage all our FoodOn editors to upgrade now. Its pretty simple.  For Mac users, downloading and opening the zip to get the Protege file: if you try to open it but get a prompt that it can’t be opened because Apple can’t verify its publisher, then go to System Preferences, Security and Privacy, General tab and you should see Protege listed under “Allow Apps downloaded from”.  Open / activate it there
