### ISSUE TITLE
New term request

### ISSUE THREAD

**Issue by zhengj2007** [FoodOntology/foodon#28]
I am working on annotation of clinical epidemiology studies using ontologies. There are few terms I think might be in FOODON scope. If Foodon would like to take the terms, I'd like to provide details if required.

Here are the terms:
- diet
- feeding
- number of meals per day

**Comment by Public-Health-Bioinformatics** [comment]
So I know FoodOn would like the "diet" term - and we plan to add comprehensive list of ("non-branded") diets, vegan, vegetarian, paleo etc.  Your definition of "diet" would be appreciated.

I see GO has "feeding behaviour": https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007631  .  Do you have something different in mind there?  I discussed with Pier Buttigieg, and we'll probably bring this process term in and axiomatize the various new ENVO eating related buildings as sites for that behaviour.

Also I'm wondering if "number of meals a day" could fit in EFO better:  https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007829  . I ask because it seems like an experimental variable or observation.

**Comment by zhengj2007** [comment]
@Public-Health-Bioinformatics Thanks for your response.

It's great that FoodOn will take 'diet' term.

Thanks for pointing to GO:feeding behavior. I feel what we need is different from it. We need the term for annotation of baby feeding, such as breast feeding, exclusively formula feeding, exclusively breast feeding.

"number of meals a day" is used for evaluation of socioeconomic conditions of a household. I am not so sure which ontology is a home of it. I thought it might be useful term in FOODON. But it is fine. We can leave it in our internal ontology.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I think those feeding processes should be in Foodon too.  So if you could send us some definitions we can implement soon.  Much appreciated.

**Comment by zhengj2007** [comment]
OK. I will do it.

Thanks!

**Comment by mateolan** [comment]
Jie et al, I think that this may work for your immediate needs but going
forward, I do believe that we'll require a separate eating ontology
<https://github.com/IC-FOODS/uc_Eating> like the one being developed by
Kimi Taji--and currently in alpha state.
I am including Kimi and Tarini Naravane (a new student who will also be
working on this) on cc so they can coordinate.
As I mentioned, this is in alpha state, without links to real definitions
yet, and not yet up to OBO standards--but with vocabularies sourced from
many different standardized diet and eating-habit interrogation tools.
(Kimi and Tarini, please subscribe to FoodOn).
~mc

**Comment by ddooley** [comment]
@zhengj2007 ping re. defs for breast feeding, exclusively formula feeding, exclusively breast feeding.

**Comment by zhengj2007** [comment]
@mateolan Thanks for the information. Our clinical epidemiology projects have many food, diet related terms. If you are planning to develop eating ontology, could you please let us know? We'd like to be involved in.

@ddooley John judkins is an ontologist who joined our group recently. He is working on the definitions of the terms we need. 

@johnwjudkins Could you please help on providing the definitions of breast feeding, exclusively formula feeding, exclusively breast feeding? Thanks!

**Comment by johnwjudkins** [comment]
Breastfeeding as a process is already in EuPath [here](http://purl.obolibrary.org/obo/EUPATH_0010371).

The other two seem to me to describe diets rather than processes, so I suggest these definitions (and labels):

'exclusive formula diet': [a child's diet](http://purl.obolibrary.org/obo/EUPATH_0000584) that includes only infant formula

'exclusive breast milk diet': a child's diet that includes only breast milk

**Comment by ddooley** [comment]
Currently FoodOn  has some age distinctions about children/infants/toddlers:

child consumer, less than four years
	infant or toddler consumer
	infant consumer
		infant consumer, 0 - 6 months
		infant consumer, 6 - 12 months
	toddler consumer, 12 months and onwards

I assume all of those are ok if we say these definitions pertain to "child consumer, less than four years" or might we run into problems with the 4 year bound?
Can we avoid "only" and say instead:

> 'exclusive formula diet': "a child's diet that includes infant formula and not breast milk.
> 'exclusive breast milk diet': a child's diet that includes breast milk and not infant formula.

This allows the kids to have juice, water, tea, etc.
Maybe insert "primarily" if need be?
Interesting to see diets as protocol processes, makes sense.

I'll consider putting EuPath's "child's diet" / "host's diet" into FoodOn too.

**Comment by ddooley** [comment]
We've added eupath child's diet" / "host's diet.

@johnwjudkins for host's diet you state: "type of diet depending on the host, for animals omnivore, herbivore etc., for humans high-fat, meditteranean etc.; can include multiple diet types"

Were you planning to create entities for these in EuPath?

I know of the USDA ones: 
US-Style Pattern
Mediterranean-style
Vegetarian/vegan
Low-carbohydrate diet
High-fat diet
Dietary Approaches to Stop Hypertension (DASH)
Dietary Guidelines-related

I have USDA references for them.  Would you consider their "natural" home in FoodOn? We need them for our USDA work. I will define them in FoodOn if you like!

Damion

**Comment by johnwjudkins** [comment]
Thanks @ddooley . We're not planning to add those entities at the moment, but I agree that they belong in FoodOn, and we might want to break down diets in such a way in the future, so having these terms defined could end up being useful to us.

**Comment by ddooley** [comment]
All the dietary terms are now destined for ONS, the Ontology for Nutritional Solutions - which will be coming online soon.
