### ISSUE TITLE
Use case: helping OAE to axiomatize some classes

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#3]
See under: http://purl.obolibrary.org/obo/OAE_0000007

Are the 4 implicit classes here in scope for foodon?

**Comment by pbuttigieg** [comment]
I think so, if we're broad with the definition of `food role` (which I 
think we should be). The class`dietary supplement` can be treated as 
bearing a food role, but it may not be classified as food by some 
authorities. The class `nutritional product may be a bit broad, perhaps 
even synonymous with "all products bearing a food role" -`product` is 
the interesting bit there.

**Comment by cmungall** [comment]
good points, now I stop to think a bit more I think we need more feedback from OAE on the use cases for these classes.

I assume there is no mechanistic difference between these 4 classes, OAEs interest in naming them is for regulatory purposes. This all gets a bit odd for a process ontology, as at least I am tuned to thinking of process ontologies in broadly scientific terms. For example, I'm OK with my bottle of AcmeGreenJuice diachronically switching from being an instance of NutritionalSupplement to JunkFood when I cross a border. But let's say I start vomiting from drinking it, but this is delayed until after I cross the border. How is the process classified? Based on where I am doing the vomiting, or where I bought the juice? I don't think a scientific ontology should be about making these kinds of angels on a pin distinctions, this seems more in line with what should be in http://www.ontobee.org/ontology/AERO, it's on the side of reporting and social structures.

**Comment by cmungall** [comment]
I will report on the OAE tracker as soon as they get off of sourceforge..

**Comment by Public-Health-Bioinformatics** [comment]
Is OAE confining itself to vocabulary only related to responses to treatment? If so then I understand certain omissions in its ontology hierarchy.  Otherwise...

I wish OAE had started off adverse event category with "ingested substance adverse event" then moved into types of ingested substance, with next dichotomy being non-foods (engine oil, bleach etc.) and "food substance adverse event" then into what type of food substance caused the adverse event.  

If I get your drift Pier, use of "product" rather than substance is a bit awkward since it implies human manufacture? As opposed to eating hand-picked wild blueberries? 

Just to describe my own current mindset on one issue: I am wary of some cases when compound terms get compiled into single terms rather than remaining separate conjunctions (in a knowledge-base), especially where the number of permutations is high.  If the possible types of food that cause an adverse event is small, then I accept that compound ontology terms can be set aside for each.  So far we have infant formula, hospital food, dietary supplement, nutritional supplement related AE's.  Why "hospital food" but not "food"?  It leaves the food allergen domain in an awkward place.

**Comment by mcourtot** [comment]
@cmungall: maybe ping Oliver separately re tracker? 

My concern with OAE is that there is no way to know that you are vomiting because you drank AcmeGreenJuice  - there is only a temporal association - unless they updated their definition of adverse event? 

induced by, http://purl.obolibrary.org/obo/OAE_0000025, is defined as 'Definition: A preceded_by relation that indicates that one process (e.g., an adverse event) is causally preceded by (induced by) another process (e.g., a medical intervention) and there is a causal relation between these two processes. This relation indicates the existence of a causal chain, meaning many processes may occur in between these two processes.'
This strikes me as wrong: the definition of the relation is ok, but its application is not IMO. I had written some docs about causality inference in medical cases, based on Pearl's (https://en.wikipedia.org/wiki/Judea_Pearl) but it seems they didn't survive the github export.

You are right that the issue AERO was trying to address is more of a guideline one - for example 'vomiting' may be a relevant symptom/sign for an anaphylaxis AE in Canada (i.e. after crossing the border) but not in the US, so you'd get diagnosed differently. If you are only interested in abnormal processes temporally associated with ingestion of food products then you may not need to go to that extent.
