### ISSUE TITLE
general question about top level hierarchy of FOODON

### ISSUE THREAD

**Issue by lcdaugherty** [FoodOntology/foodon#303]
Hi
I am thinking using FOODON for my dataset and was looking at the hierarchy structure (via OLS https://www.ebi.ac.uk/ols4/ontologies/foodon?tab=classes&viewMode=tree). 

Currently the top level structure includes terms I would not expect to be there:

eg:  [apricot juice],  [knish] etc
<img width="660" alt="Screenshot 2024-03-03 145356" src="https://github.com/FoodOntology/foodon/assets/14925172/a7917e4b-deb8-454a-875d-fb0cabf323c2">

I have previously worked within the human disease/biology domain so have in the past contributed extensively to MONDO/GO ontologies, so I am just wondering if FOODON ontology is relatively new and therefore is still very much an evolving ontology in comparison?

**Comment by ddooley** [comment]
Hi, Thanks for reporting this.  What is happening is that the built version of FoodOn can trigger the placement of top-level terms that our source code files don't make apparent. I'll correct the parentage of the top level terms so they reflect where they are within the /src/ontology/foodon-edit.ofn file.  Sometimes this has to do with processing that OLS is doing that we don't anticipate on the /foodon.owl file. 

[Addendum: it turns out Protege was automatically visually placing "X subclass of Y and Z" subclass axioms, whereas OLS wasn't, causing terms with such expressions to float to top of hierarchy.  This is fixed].

For our term development, we're still in the process of revising hierarchies of terms that were inherited from LanguaL, a very longstanding food composition term thesaurus, and from a SIREN database of food products.  As well receiving new terms from PTFI project and USDA FDC mappings as well as introducing standardized templates for animal and plant material.  So various changes yes, but we are trying to provide continuity of hierarchic access to foods/ingredients.

**Comment by ddooley** [comment]
I will close this now, but feel free to reopen if further action is needed.
