### ISSUE TITLE
has_dbxref URLs not resolving

### ISSUE THREAD

**Issue by NutrientInstitute** [FoodOntology/foodon#314]
Every has_dbxref link leads to a page that says "Unable to resolve entries in siren"

For example, food (raw) ([FOODON:03311126](https://www.ebi.ac.uk/ols4/ontologies/foodon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFOODON_03311126?lang=en)) has db_xref [https://bioregistry.io/reference/siren:F11126)](https://bioregistry.io/reference/siren:F11126). 

![image](https://github.com/FoodOntology/foodon/assets/128626166/360a8e61-c0c7-4059-b34f-4263c5f60525)

**Comment by ddooley** [comment]
Yes, these URLS don't resolve in the bioregistry siren version because they don't resolve anywhere on internet.  There is no resolution for them beyond the code's presence in document mentioned in bioregistry as "other" -> https://www.langual.org/download/IndexedDatasets/FDA/SIREN%20(updated).TXT  
Unfortunately bioregistry doesn't have a gentler way of communicating this!
