### ISSUE TITLE
NTRs: solid and liquid food

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#35]
Greetings! 

Could we include defined classes, to be filled by inference alone, for solid and liquid food?

ENVO does this for materials ([liquid](http://purl.obolibrary.org/obo/ENVO_01000815), [solid](http://purl.obolibrary.org/obo/ENVO_01000814).

This would be very useful prepacking for other ontologies like ECOCORE and NBO.

**Comment by Public-Health-Bioinformatics** [comment]
So FoodOn currently has the following inherited from LanguaL.  Its interesting in that they recognize more gradations between solid and liquid: http://purl.obolibrary.org/obo/FOODON_03430113

    - physical state, shape or form
        + semiliquid
        - physical state, shape or form, multiple
        + liquid
        + semisolid
        + solid
        + supplement form

The plain definitions for liquid and solid are interesting in that for liquids a viscosity range is indicated, while for solids they define a temperature at which to judge the material state.  I see only FMA offers terms for solid and liquid quality elsewhere in OBOFoundry, with no defs.  [EDIT: drop this, doesn't pertain to above qualities: I will add to FoodOn's liquid and solid terms the same 'has quality' some PATO qualities as ENVO has for substances.]  Perhaps we should add some kind of temperature environmental qualifier too.  I may take in FMA's solid/liquid term ids, but would need them then to accept our definitions.

**Comment by Public-Health-Bioinformatics** [comment]
Also, foodon could just offer up a "solid material quality" rather than the more narrow "solid food quality" (and similarly for the other material states) since the thing being described would have a food quality or "role of food" separately?

P.s. looks like there is something odd in ENVO as seen in OLS and Ontobee - "solid environmental material" is at moment placed under "ice".

**Comment by Public-Health-Bioinformatics** [comment]
I will add "solid food" and "liquid food" as materials that have given qualities.

**Comment by leechuck** [comment]
This will still need "liquid" and "solid" (and "gaseous" and "plasma" and possibly other non-classical and low temperature states) in PATO to provide the qualities.

**Comment by Public-Health-Bioinformatics** [comment]
I've just introduced a swath of product type categories suggested by the SIREN food database content.  Two new terms:
FOODON_03305105: food product, liquid
FOODON_03317643: food product, solid
I will be axiomatizing them next week; have run out of time at the moment.

**Comment by Public-Health-Bioinformatics** [comment]
I have defined:

food product, solid: equivalent to: 'food material' and 'has quality' some PATO 'quality of a solid'
food product, liquid: equivalent to: 'food material' and 'has quality' some PATO 'quality of a liquid'

Not sure about any qualities in between (e.g. filling-removing toffee)!

**Comment by mateolan** [comment]
This is another one where we should be looking to map to an external
ontology, in this case, matter/state. Damion, I think you have seen our
preliminar model for food physical properties... I'm guessing our
colleagues in material science have a much better grasp on this. We'll need
to represent things like dough with solid parts like chocolate chips, as
well as liquid-filled solids. We should also think of granular solids that
act like liquids because of their pourability. The physical properties
aspect is something we have spent a fair amount of time on, and know that
we need to link to specific types of processing.  ..this is something we
can talk about further, and perhaps even begin to model,  in the workshop
on November 8th.

On Oct 2, 2017 16:03, "Damion Dooley" <notifications@github.com> wrote:

I have defined:

food product, solid: equivalent to: 'food material' and 'has quality' some
'quality of a solid'
food product, liquid: equivalent to: 'food material' and 'has quality' some
'quality of a liquid'

Not sure about any qualities in between (e.g. filling-removing toffee)!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FoodOntology/foodon/issues/35#issuecomment-333689745>,
or mute the thread

**Comment by Public-Health-Bioinformatics** [comment]
Matthew, perhaps the people you have working on this could engage directly with PATO since that seems to be the OBOFoundry ontology that comes closest to covering the physicality of substance? I'm getting viscous, etc. in from there.  See http://purl.obolibrary.org/obo/PATO_0001018 .  They certainly need flavour enhanced!

**Comment by ddooley** [comment]
Closing this as generic solid/liquid food classes were achieved.
