### ISSUE TITLE
Release of foodon should always have asserted superclasses

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#47]
melon seed has no superclass http://purl.obolibrary.org/obo/FOODON_03307879

Consider using `robot relax`

**Comment by cmungall** [comment]
OK, multiple problems here:

`melon fruit food product and (has part only seed)`

 1. dubious. The definition is inclusive of mereological sums of seeds
 2. transitive properties can't be used in combination with universal restrictions. Consider: nothing has-part only seeds. If X has-part seed, then X has-part endoderm, endoderm is not a seed, therefore X is unsatisfiable. I think you need hermit/fact to see this

**Comment by pbuttigieg** [comment]
In general, I think FOODON needs to be a bit more cautious with the automated/sweeping assertions. @Public-Health-Bioinformatics we should consider having an extended call to go through some of the top-levels.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, fixed 'melon seed'. Superclass must have accidentally been deleted.

I'd welcome a call on the axiomatization, I appreciate the advice... I'll connect to find a good time.

About "melon fruit food product and (has part only seed)" , that should have been:

    'melon fruit food product' and ('has part' some seed and 'has part' only seed)

Now fixed. Now the way I was expecting that to semantically ring true is that 'melon seed' is a descendant of 'melon food product', defined as:

    'cucurbit fruit food product' and ('derives from' some 'melon plant (food source)')

So 'melon seed' is a food product deriving from some 'melon plant (food source)' and only having part seed.  Can that be improved some how?  'melon plant (food source)' has subclasses, some of which point to specific plants via NCBITaxon. The remainder will eventually have NCBITaxon info.

**Comment by Public-Health-Bioinformatics** [comment]
By the way my approach is to have at least one explicit superclass for any class. As well, if there is an equivalency axiom for the class, the explicit superclass should be mentioned as the leading term in it (as a conjunction term). This guarantees a hierarchic structure for users who aren't using a reasoner.  But I see now what your "robot relax" transformation does to this end too, @cmungall .

**Comment by cmungall** [comment]
Better!

The only+transitive issue remains. I'd recommend thinking very carefully about  universal restrictions in general. As well as being outside the scope of what can be reasoned in Elk, they are a minefield for modeling errors. I think there should be a feature in Protege where a paperclip pops up whenever you use an `only` where it says "are you SURE you need this?"

Some other issues - your axiom means that wild melon seeds are food products. I thought the modeling pattern in foodon is that a material entity must have a food role to be food products.

What is wrong with 'melon seed = seed and part-of some NCBITaxon:melon'?

**Comment by Public-Health-Bioinformatics** [comment]
I'll look at the transitivity issue next week to understand what you mean.

'melon seed' inherits "'environment material' and 'has role' some food" via "food material" -> "plant food product"... so wild melon seeds can be food products if fulfilling the food role. (I suppose 'has role' some food" could be added to top level "food product type" too, although chemical additives may preclude this move.)

In FoodOn we have a separate "food source" branch that currently attempts to enumerate all plants and animal organisms as a whole that are used as food sources by humans (and domesticated/agri animals), but this this is not directly a biological taxonomy hierarchy for a few reasons. I've made the deliberate move to separate out linguistic reference to food organism from reference to taxonomy.  We aspire to cross reference each food source item with an NCBITaxon or other taxonomy identifier, but since NCBITaxon is not the only taxonomy in town, I set it up that each "food source" branch entity becomes the focus on which cross reference to taxonomic identifiers like NCBITaxon occur. This allows food source reference to organism in the face of changing taxonomies, or lack of taxon info. 

Now there is some debate about whether 'food source' and 'food product type' should be merged, but it is clear to see that references within 'food product type' to 'food source' organisms indicate one has hit "rock bottom" in the food processing chain.

Earlier I considered 

    'melon seed = seed and 'derives from' some 'melon plant (food source)'

with 'melon plant (food source)' referencing NCBITaxon. I would like to talk about this on a call. One thing I don't like is that the PO plant ontology hierarchy suddenly starts getting food products placed under its classes like "seed" (even without using a reasoner in protege). So what was a PO hierarchy of anatomy parts/features suddenly gets product variations under it, essentially a shift in paradigm of the hierarchy. But if that is acceptable to the community, then I can run with it.

**Comment by Public-Health-Bioinformatics** [comment]
@cmungall I see point that a universe containing 'melon seed: equivalent to 'melon food product' and 'has part' only seed' can't coexist with a set of claims that infer a whole (normal) organism from the existence of one of its parts, as an anatomy ontology might bundle up.  " X has-part seed -> X has-part endoderm" etc.  So are we talking here about how one ontology or rule engine's use of 'part of' would clash with FoodOn's? A solution then would be to switch to using a less-general purpose object relation like 'has ingredient' ?

To understand none and transitivity, I tried to express your problem model in protege and ran against hermit/fact, but didn't run up against contradiction, so can you see what I'm missing? I presume I don't need instance data to see it? Is problem more about rule engine implication than it is about object relation transitivity? 

    classes
    seed: disjoint with endoderm
    endoderm: disjoint with seed
    plant: equivalent to: 'has part' some seed and 'has part' some endoderm 
    melon seed: equivalent to 'melon product' and 'has part' only seed  // + 'has part' some seed
    melon product: disjoint with 'non-melon product'
    non-melon product: disjoint with 'melon product'

    object relations
    'has part': transitive

**Comment by cmungall** [comment]
On 23 May 2018, at 0:57, Damion Dooley wrote:

> @cmungall I see point that a universe containing 'melon seed: 
> equivalent to 'melon food product' and 'has part' only seed' can't 
> coexist with a set of claims that infer a whole (normal) organism from 
> the existence of one of its parts, as an anatomy ontology might bundle 
> up.

I think you're saying the incoherency is only revealed when combined 
with an anatomy ontology - in this instance yes, but it's not hard to 
come up with trivial examples where the mix of universal+transitive is 
incoherent in a single ontology.

> " X has-part seed -> X has-part endoderm" etc.  So are we talking here 
> about how one ontology or rule engine's use of 'part of' would clash 
> with FoodOn's?

No I think it's more basic

> A solution then would be to switch to using a less-general purpose 
> object relation like 'has ingredient' ?

a more specific property can work

> To understand none and transitivity, I tried to express your problem 
> model in protege and ran against hermit/fact, but didn't run up 
> against contradiction, so can you see what I'm missing? I presume I 
> don't need instance data to see it?

No

> Is problem more about rule engine implication than it is about object 
> relation transitivity?

Not sure what you mean by rule engine implication, it's not about any 
particular rule engine

>
>     classes
>     seed: disjoint with endoderm
>     endoderm: disjoint with seed
>     plant: equivalent to: 'has part' some seed and 'has part' some 
> endoderm
>     melon seed: equivalent to 'melon product' and 'has part' only seed 
>  // + 'has part' some seed
>     melon product: disjoint with 'non-melon product'
>     non-melon product: disjoint with 'melon product'
>
>     object relations
>     'has part': transitive

you need to express the relationship between seed and endoderm

**Comment by Public-Health-Bioinformatics** [comment]
Ok, what was throwing me was that I couldn't find "endoderm" in relation to the seed itself (my botany knowledge is minimal so I'm looking at https://en.wikipedia.org/wiki/Seed). So I think "endosperm" is what the test calls for, so I'm rejigging it for that.  Thanks.

**Comment by Public-Health-Bioinformatics** [comment]
I get it crystal clear now. In using the "only" constraint in conjunction with a transitive relation 'has part', e.g. "X has part only A", transitivity allows an axiom "A has part some B" to yield "X has part some B", a contradiction.  So all uses of "only" cannot involve transitive relations. Which is what you said! Oy.

**Comment by Public-Health-Bioinformatics** [comment]
I've dropped the "only" part and made it a subclass axiom.  The equivalency was experimental - i.e. the only food product using an "has part only ..." axiom - so fortunately no other changes to FoodOn required in this respect.
