### ISSUE TITLE
NTR: Consider adding specific diets

### ISSUE THREAD

**Issue by LCCarmody** [FoodOntology/foodon#74]
Hi All,
We are currently adding diet and supplement restrictions, but some terms may be more suited for FOODON.  I am listing a few that are higher on our list.   I don't have an easy answer to where in FOODON these should go. There is a term diet meal, liquid (FOODON_03302872) but that is a child of 'food product', so I don't think that is a natural placement.
Thanks.

Term | in Maxo | Definition | Definition source | Synonym | Foodon Term
-- | -- | -- | -- | -- | --
vegetarian   diet | no/will not add currently |   |   |   |  
vegan   diet | no/will not add currently |   |   |   |  
Low-carbohydrate,   high-protien, high fat diet | no | The   low-carbohydrate, non–restricted-calorie diet aimed to provide 20 g of   carbohydrates per day for the 2-month induction phase and immediately after   religious holidays, with a gradual increase to a maximum of 120 g per day to   maintain the weight loss. | PMID:18635428 | Low carbohydrate diet
Meditteranean   diet | no | The moderate-fat, restricted-calorie,   Mediterranean diet was rich in vegetables and low in red meat, with poultry   and fish replacing beef and lamb. | PMID:18635428 |   |  
low fat   diet | no | A   restricted-energy diet with less than 30 % of energy from fat. | PMID:23651522 |   | low fat food FOODON_03510039
intermittent   fasting | no | Intermittent fasting is a form   of time restricted eating, typically 16 h fasting and 8 h eating. | PMID: 30897855 |   |  
DASH   diet | no | Dietary Approaches to Stop Hypertension   (DASH) trial, which demonstrated that consuming a diet rich in fruits,   vegetables, and low-fat dairy products and reduced in saturated fat and   cholesterol | PMID: 29141784 |   |  
ketogenic   diet | ketogenic diet intake   MAXO_0030010 | The ketogenic diet is a   high-fat, low-carbohydrate, adequate-protein diet that mimics a fasting   state, resulting in the substitution of ketone bodies as a source of energy.   The ketogenic diet can be used to reduce recurrent epileptic seizures in   individuals with intractable epilepsy. Intractable epilepsy is defined as   epilepsy that failed to respond to three or more antiepileptic drugs. | PMID:23419562, PMID:27759811,   PMID:28701250 | Modified Atkins diet
fasting | fasting intervention   MAXO_0000098 | Going without food or drink for   a certain period of time. | PMID: 30897855 |   |  
Low   calorie diet | calorie restrictive diet intake   MAXO_0000089 |   |   |   | low calorie food FOODON_03315839
texture   modified diet | texture modified diet intake   MAXO_0030011 |   |   |   |  

https://github.com/monarch-initiative/MAxO/issues/66
https://github.com/monarch-initiative/MAxO/issues/82
https://github.com/monarch-initiative/MAxO/issues/94

@laurenechan

**Comment by ddooley** [comment]
Indeed diet meal is a material entity reference, whereas diet seems to speak to a pattern of behaviour.  We've had some past discussion about this (https://github.com/EcologicalSemantics/ecocore/issues/108 @pbuttigieg @cmungall @diatomsRcool) and explored whether a diet is a material aggregate of sorts, or qualities, but actually, now I'm thinking **it is best considered a type of protocol,** essentially involving an inclusion criteria (http://purl.obolibrary.org/obo/OBI_0500027) but pertaining to food chosen for a food consumption processes. Whether the protocol is adhered to strictly is a different question!

If this sticks, I would be happy to bring OBI protocol into FOODON as parent of a new "food consumption protocol" and have diets as children of that, with extra "inclusion criteria" as we get into the details of what each diet requires, including consumption / fasting patterns.

**Comment by ddooley** [comment]
We'd probably use "eligibility criterion" (http://purl.obolibrary.org/obo/OBI_0500026)- both inclusion and exclusion - to define diet components. Its definition is nicely general: "an eligibility criterion (rule) is_a selection criterion which defines and states the requirements (positive or negative) for an entity to be considered as suitable for a given task or participation in a process."

The USDA tends to speak of "eating patterns" these days rather than diets.  At any rate, we would want to revise the definitions above  - using resources like https://www.dietaryguidelines.gov/sites/default/files/2019-05/2015-2020_Dietary_Guidelines.pdf . I will check in with the USDA folks we work with to see where good definition sources are from their perspective.

**Comment by laurenechan** [comment]
Agreed, this is more of a protocol!
@LCCarmody Just to make sure I understand, are you recommending to add all of these eating patterns/therapies into FOODON rather than add them into MAxO? 
I am primarily wondering if we are then limiting representation of any nutrition therapies in MAxO should we choose to not include things such as a ketogenic diet, which is a prescribed medical nutrition therapy. There are some separations between medically prescribed nutrition recommendations and more of a lifestyle eating pattern, but therapeutic diets should likely still be represented in MAxO I would think.

**Comment by ddooley** [comment]
Tried to solve this more as a result of cmungall's and diatomsRcool examples on EcologicalSemantics/ecocore#108 .  New term proposals are there that fit into BFO / IAO / OBI paradigm.  I'll repeat them here for feedback:

This one has broad synonym of "diet" because it is a more specific sense of diet:
 
label: '**ingested food set**': 
subClassOf: 'object aggregate'
definition: 'A comprehensive set of food items which an organism has ingested over some span of time.'
hasBroadSynonym: diet
elucidation: 'This names various food items an organism has ingested. The quantity or mass of the items is not indicated.'

This could be derived from:

label: '**ingested food log**'
subClassOf: IAO "data set".  
definition: 'A set of food consumption events detailing food ingested and the time of ingestion.'
elucidation: 'This may include the mass or quantity of a food item, and other details such as its preparation process.'

label: '**ingested food**' (EDIT: not necessary, it exists in UBERON)
subClassOf: "food material".  
definition: 'A food material consumed by an organism at some point or duration in time.'

... one could add terms for other statistics derived from the ingested food log

Another sense of diet is as a defined set of food proportions, so not referencing material entities directly. The proportions are with respect to some open-ended "norm", or with respect more particular food groups.  Outright exclusions are needed, e.g. "A vegan diet contains no animal products."

Technically this sense of diet sounds a lot like a "dataset of features" (http://purl.obolibrary.org/obo/OBI_0000649) about an organism's ingested food:  _A data set that is produced as the output of a descriptive statistical calculation data transformation and consists of producing a data set that represents one or more features of interest about the input data set._ .  If we allow a looser interpretation of "descriptive statistical calculation", then this would cover both intentional plan/goal and descriptive perspectives, and could include constraints on timing of ingestion, so could cover fasting regimes.  I'll check with OBI folks on monday about this.

label: "**diet**"
subClassOf: OBI 'dataset of features' and 'is about' some 'ingested food'
definition: 'A set of generalizations about an organism's ingested food'

label: "**mediterranean diet**"
subClassOf: diet
definition: 'A diet emphasizing vegetables, fruits, herbs, nuts, beans and whole grains, and allowing moderate amounts of dairy, poultry, eggs, and seafood, and a lower intake of red meat.'

etc.  One could add  "objective specification" parts that contain diet constraints.

**Comment by ddooley** [comment]
OBI call was informative. Call reinforced not to mint a basic "diet" term. All the more particular senses of diet live in different places in BFO etc. class/concept hierarchy. Instead, to connect the word "diet" as people might use it in a search engine to these varied term entities, we can use the  hasBroadSynonym annotation.

'**ingested food log**' survived critique in the call as a clear case of a data set.  Should we label it as "... log" or "... record" or "... data set"?

And I just found "**ingested food**" already exists as an UBERON term so we will reuse that.

The '**ingested food set**' was agreeable but it does sound problematic to have it be an "object aggregate" as the aggregate is intended to reference a collection of object instances at some time t, whereas the proposed set is only meant to reference the **classes** or types of food eaten.  So I would revise ingested food set to be a type of dataset too, derived from the food log dataset. May only need to add this term in the future. 

The above "diet" was discouraged as the "dataset of features" parent was too tied to parameters of an actual dataset.  People preferred "dietary regimen" as a subclass of protocol, so - and here I welcome definition edits - something like:

label: "**dietary regimen**"
subClassOf: protocol
hasBroadSynonym: diet
definition: "A set of restrictions on food type ingestion and/or timing of food ingestion"

Another suggestion was to define classes of dietary food - a "vegetarian food", a "carnivorous food" - here one can define in an equivalency exactly what is permitted or not in the class by reference to other food types.  I really like this.  Under "FoodOn product type, I would add a convenience class  "food product by dietary group" class to gather the various diet categories.

label: "**food product by dietary grouping**"
subClassOf: "FoodOn product type"
definition: "A food item categorized by a dietary group of food"

Then subclasses can have equivalency axioms that spell out the dietary group:

label: "**pescatarian food**"
subClassOf: "food product by dietary grouping"
definition: "A dietary group of food that does not include land-based animals or animal products, but does allow freshwater- or saltwater-based animal products."
equivalentTo: "'food material' and not ('meat food product' or 'avian food product' or 'dairy food product') "

The https://www.dietaryguidelines.gov/sites/default/files/2019-05/2015-2020_Dietary_Guidelines.pdf document conveys in its "eating patterns" not just the set of foods to eat, but also amounts, so I avoided using "eating pattern" in label as it carries this extra level of detail.

We can then simply say some organism is 'consumer of' [some | only] 'pescatarian food'.  (It isn't defined in RO at moment but 'consumer of' is reverse of 'has consumer'.)

An experimental process can [paraphrasing] have an associated 'dietary regimen' protocol with objective (objective specification) to provide  'oral administration' (a planned process) of certain food (a 'food product by dietary group') according to some schedule.

**Comment by mellybelly** [comment]
@ddooley are there notes from the OBI call? @laurenechan is implementing our dietary interventions in Maxo (she is a registered dietitian) and it would be great for her to participate in the future. 

I do think we need to think more about dietary regiments- there are similar to a protocol but also have dynamic and behavioral aspects. These are in fact what we need for interventions and disease causal relationships (e.g. exacerbates or causes).

We probably need greater community coordination and discussion before any design patterns are implemented - where should we have these discussions?

**Comment by ddooley** [comment]
I didn't take any notes (my little word scribbles don't really count), but can recount that Chris S. was advocating for real study data to use as a basis to describe diet related terms from (sounds like you could provide some!); while Bjorn was happy to see curation work proceeding on diet as it related to protocol, with the analogy of protocols related to drug administration to patients  in certain amounts/times of day.  We talked about diet and poked holes in above "diet" definition, leading to my response above. 

I would be happy to engage with Lauren and others on this more.  If she wanted to present to the OBI group in January on the dietary regime/nt and explain protocol parts and beyond, and clinical study needs, I  think that would be welcome - I can verify with the OBI group.  

I foresee FoodOn housing diet related food groups but would accept other curation teams taking the lead there too.  The ECOCORE folks certainly have a parallel interest in capturing food system related diet.  Alternately, outside of the OBI call, in January we could organize a telecon on the subject?

**Comment by ddooley** [comment]
BTW I'd like to see these diets added too: Lacto-vegetarian, Ovo-vegetarian, Lacto-ovo vegetarian diet, and a semivegetarian diet — also called a flexitarian diet — which is primarily a plant-based diet but includes meat, dairy, eggs, poultry and fish on occasion or in small quantities. (source: https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/vegetarian-diet/art-20046446)

**Comment by LCCarmody** [comment]
I support this for terms, but for MAxO...we mainly get recommendations for 'Supplement X if vegetarian/Vegan', but I think more granular terms could be useful.

**Comment by ddooley** [comment]
Ok.  For FoodOn application to websites like https://fdc.nal.usda.gov/ (which we are working on) I'm thinking here of being able to select a diet (or indirectly, a list of foods), and then be able to calculate which nutrients may need special attention (supplementation or particular food sourcing) as a result.  Understanding of course that food preparation and individual nutrient uptake are wildcards.

**Comment by ddooley** [comment]
A diagram that in my view disambiguates types of dietary / eating pattern term.  Feedback welcome:  - AND I fixed spelling error: I meant "prescribed"!

![image](https://user-images.githubusercontent.com/4000582/79767686-868d9e00-82de-11ea-84bf-62d567193d87.png)


And a list of fasting and food-specific diets - not complete but potential organizing scheme

![image](https://user-images.githubusercontent.com/4000582/79642031-02a5ab80-8150-11ea-82fd-30132db88598.png)

**Comment by laurenechan** [comment]
@ddooley 
Is there a particular reason we are using proscribed as opposed to prescribed?

Also, looking at the 'diet by type of food' --> 'composition' sections, what are you proposing we guide the "high" or "low" values off of for indicating composition? Would we use percentages of acceptable macronutrient distribution ranges or some other guideline?

Further, I think we may reconsider "ketogenic" as a term for composition as you will get a huge number of foods that fall into that category. Ketogenic simply describes production of ketones in the body, but ketones are produced by all humans throughout the day with lipid breakdown even in someone who is not observing a 'classic ketogenic diet'. As any substrate can become lipid and lipid catabolism can happen in a human fed any substrate, this could arguably encompass a huge amount of foods.

Additionally, achievement of ketosis (the goal for a ketogenic diet) also relies on timing of substrate consumption, i.e. if you have 30g carb throughout the day in small quantities you are more likely to maintain ketosis, whereas if you had all 30g at one time, some human bodies will not maintain ketosis. While I understand the means to try and include this as a composition factor, we may consider just focusing on macronutrient content labels as opposed to functional labels to ensure we can clearly define the classes.

**Comment by LCCarmody** [comment]
My 2 cents: Halal diet is unlikely to be prescribed, but it may be proscribed. Conversely, vegetarian may be proscribed or prescribed or just a preference.  Not sure if there is a term that encapsulates all 3. I don't think we should necessarily divide them.

I don't think we need to have terms that breakdown composition too specifically. Higher and lower might be subjective, but I think that's preferable because there are different situations.  Maybe textual defines could be 'higher than normal' or 'higher than baseline' or something that could fit a number of circumstances. 

I have no opinion on ketogenic--  Maybe textual definitions and comment field can cover some of the information?

**Comment by ddooley** [comment]
Oy - that was my spelling mistake.  I meant "prescribed"!  Fixed above.  But good point Leigh, there seems to be a middle space as well for cultural diets - "practiced" might be better than "prescribed" in a number of cases.  And then advice not to eat a certain way.  So possibly proscribed/prescribed/practiced diet are their own stand-alone terms, and we don't place other diet categories under them - but this suggests building a bit of a model to capture who is doing the prescribing / proscribing. Something that could be done later.

And I would be fine relabeling "high fat / low fat" to "higher than normal" and "lower than normal" fat intake.

We could discuss having diet terms defined so they can at least be used in text mining without necessarily expecting to link them to food categories.

**Comment by LCCarmody** [comment]
Our biggest concern for text mining is to include synonyms of how they might be stated in the literature. So, if 'higher than normal fat diet' is the term label, we might have 'high fat diet' as a synonym.  We currently do use annotation properties for exact, narrow, and broad synonyms to try bridge what things are commonly referred to with the exact concept.  Does FoodOn use those annotation properties?

**Comment by ddooley** [comment]
Yes FoodOn uses the oboInOwl broad and narrow and exact synonym.  And we try to keep them well populated, especially the exact one.  We also use the language attribute with all labels and synonyms.

**Comment by ddooley** [comment]
Diet vocabulary is now on its way to being incorporated in ONS.
