### ISSUE TITLE
Relationship between food source, food material, and food product

### ISSUE THREAD

**Issue by ramonawalls** [FoodOntology/foodon#80]
Reading the text definitions, it seems like all food materials are ultimately derived from some food source. Is this true? 

I'm also not sure what the distinction is between a food material and a food product type and why one is a subclass of the other, especially since food product type is the only subclass.

**Comment by ramonawalls** [comment]
@lilyandres

**Comment by ddooley** [comment]
The food source branch is meant to house a reference to a whole plant or animal / algae / fungi, and can function outside the context of food actually, as in cow being referenced in a veterinary context.  But as soon as some processing is applied to an organism to turn it into food - harvesting, chopping, cleaning etc. it starts being talked about from the perspective of a food product - and all the modelling that entails. That's why there is a second food product branch.  The one place that breaks down a bit so far is that many fish and other seafood organisms are treated as products as a whole, so they are listed under food product right now too.  

About food material class structure, I was going to talk with Pier B. about organizing that with respect to ENVO a bit better.  A discussion you would like to be involved in?

**Comment by ramonawalls** [comment]
Thanks, @ddooley . Do you think it makes sense to explicitly add a relation like `food product derived from food material`? 

Yes, I would like to take part in the discussion about the food material class structure.

**Comment by ddooley** [comment]
Yes, could do that at top level, will check that out.

**Comment by LilyAndres** [comment]
Hi, Thanks Ramona! @ddooley we were thinking of reuse some of the terminologies from FoodOn, but the "plant" from "food source" class doesn't relate to what we want to describe. We want to describe the concentration of some nutritional components in different legumes. I was thinking that "grain plant" from "grain or seed-producing plant" could help with our goals but of course they are food sources, rather than nutritional components or plant materials. It could be great to have a new class such as "**Crop dietary raw material**", happy to be part of the discussion

**Comment by ddooley** [comment]
We can look at creating a lower level food product class that points to the grains themselves rather than the plants, and finalize that here - that is a fit for FoodOn (all grains would be members though?).  But to let you know we are getting a monthly call together to discuss diet and other food ontology terminology needs, and where they will fit - not just FoodOn, but ONS, an Ontology for Nutritional Studies that is on its way to OBOFoundry, and any other relevant food related ontology.  I.e. a discussion among peers.

**Comment by ddooley** [comment]
To add - happy to complete the list of grains from specific plants, or do you likely need a matrix of them, from each of the gain plants listed?  There is the 'cereal grain food product' http://purl.obolibrary.org/obo/FOODON_00001093 class where respective grains (under possibly respective general grain plant food product classes) would go, or under 'legume food product' http://purl.obolibrary.org/obo/FOODON_00001264

**Comment by LilyAndres** [comment]
Thanks @ddooley we are planning to start with legumes (bambara, cowpea, soybean, mungbean and chickpea) but we actually would like to have the nutritional information associated to crops in general not only legumes, but you can add them as well.

**Comment by ddooley** [comment]
Just to clarify - so are the "legume food product class"  and cereal grain food product" classes ok for you to start? Under each you should find (and if you don't put in a new term request) the specific legume food product, and under that an entry for each bean or seed. When you speak of the "concentration of some nutritional components in different legumes", this requires vocabulary for the nutritional components.  We plan on adding all of the USDA ARS Food Data Central (https://fdc.nal.usda.gov/, e.g. https://fdc.nal.usda.gov/fdc-app.html#/food-details/172420/nutrients) nutritional components (all present in their SR Legacy and other databases there). We'll have an ontology id for each.  Each will be listed as a "data item", and many will have an equivalent INFOODS tag name, i.e.  one for Potassium, K, one for Ash etc.

**Comment by ddooley** [comment]
An update on this.  Upper level food material and food product relationship is clarified in new upload of FoodOn, and will be documented in foodon.org shortly.  The CDNO Crop Dietary Nutrition Ontology will be handling the FDC nutrition components which FoodOn will import.  See FoodOn and CDNO presentations coming up on Sept 16: https://foodon.org/icbo-2020-food-workshop/ . This will be recorded and displayed on FoodOn site.
